### ISSUE TITLE
Video tutorials?

### ISSUE THREAD

**Issue by gmlewis** [joushou/gocnc#15]
Hi! This looks really amazing... thank you for making it available.

Have you considered creating any video tutorials showing examples of how you use this repo?

I was searching for "golang gcode" thinking there may be a more intuitive way of actually creating the G-Code files using Go (since it is so awesome) but came across your repo which looks like it presumes the G-Code has already been created.

May I ask what you use to write your G-Code?  Do you write it manually?  (Although I've been 3D printing for almost a decade, I'm just now starting to get into G-Code and was hoping for a more natural way to write it so I don't have to memorize yet another language. :smile: ).

Thanks again!

**Comment by kennylevinsen** [comment]
gocnc is  a gcode sender and post-processor/optimizer for CNC mills.

gcode is usually generated by CAM software where you define toolpaths around the geometry of your model. Some CAD software like Fusion360 has built-in CAM functionality. You can hand-write gcode for simpler jobs, but it doesn't scale.

**Comment by gmlewis** [comment]
OK, thank you!
